version = 1
SPDX-PackageName = "datarecord"
SPDX-PackageSupplier = "energy-models Org <https://github.com/energy-models>"
SPDX-PackageDownloadLocation = "https://github.com/energy-models/datarecord"

[[annotations]]
path = ["**"]
SPDX-FileCopyrightText = "datarecord contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  ".github/pull_request_template.md",
  ".all-contributorsrc",
  "src/datarecord/py.typed",
]
SPDX-FileCopyrightText = "datarecord contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["resources/**/*"]
SPDX-FileCopyrightText = "datarecord contributors"
SPDX-License-Identifier = "CC-BY-4.0"
